/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package login;


import java.awt.Dimension;
import java.awt.GraphicsEnvironment;
import java.awt.Point;
import java.sql.Connection;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import koneksip.konek;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;


/**
 *
 * @author Asus
 */
public class menu extends javax.swing.JFrame {
    private Connection conn = new konek().connect();
    

    
    
    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
        initUI();
        Locale locale = new Locale ("id","ID");
        Locale.setDefault(locale);
    }
    
    private void initUI(){ 
                
        Dimension windowSize = getSize();
        GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        Point centerPoint = ge.getCenterPoint();
        int dx = centerPoint.x - windowSize.width / 2;
        int dy = centerPoint.y - windowSize.height / 2;   
        setLocation(dx, dy);
        
    }
    public void Hakaksespetugas(){
        mndsiswa.setEnabled(false);
        mndanggota.setEnabled(false);
        mnpbuku.setEnabled(true);
        mndpinjam.setEnabled(false);
        mnbuku.setEnabled(true);
        mndpetugas.setEnabled(true);
        mndbuku.setEnabled(true);
        mndpetugas.setEnabled(true);

    }
    
    public void Hakaksesuser(){
        mndbuku.setEnabled(false);
        mnpetugas.setEnabled(false);
        mndpetugas.setEnabled(false);
        mndinventaris.setEnabled(false);
        mndsiswa.setEnabled(true);
        mndanggota.setEnabled(true);
        mnpbuku.setEnabled(true);
        mndpinjam.setEnabled(true);
        mnbuku.setEnabled(false);
        mnpengembalian.setEnabled(false);
        mndaftarbuku1.setEnabled(false);
        jMenuItem4.setEnabled(false);
        jMenuItem6.setEnabled(false);
        jMenuItem7.setEnabled(false);
       
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jSeparator1 = new javax.swing.JSeparator();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar4 = new javax.swing.JMenuBar();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jMenuBar5 = new javax.swing.JMenuBar();
        jMenu9 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        mlogout = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        mnpetugas = new javax.swing.JButton();
        mndinventaris = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        mndaftarbuku1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        mndanggota = new javax.swing.JButton();
        mndpinjam = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mndsiswa = new javax.swing.JMenuItem();
        mndpetugas = new javax.swing.JMenuItem();
        mndbuku = new javax.swing.JMenuItem();
        transaksi = new javax.swing.JMenu();
        mnpbuku = new javax.swing.JMenuItem();
        mnbuku = new javax.swing.JMenuItem();
        laporan = new javax.swing.JMenu();
        mnpengembalian = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("File");
        jMenuBar3.add(jMenu5);

        jMenu6.setText("Edit");
        jMenuBar3.add(jMenu6);

        jMenuItem1.setText("jMenuItem1");

        jMenu7.setText("File");
        jMenuBar4.add(jMenu7);

        jMenu8.setText("Edit");
        jMenuBar4.add(jMenu8);

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jMenu9.setText("File");
        jMenuBar5.add(jMenu9);

        jMenu10.setText("Edit");
        jMenuBar5.add(jMenu10);

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));
        jPanel2.setLayout(null);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/download.jpg"))); // NOI18N
        jPanel2.add(jLabel4);
        jLabel4.setBounds(260, 30, 57, 57);

        jLabel3.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        jLabel3.setText("SMP Muhammadiyah 3 Cisalak");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(190, 130, 220, 20);

        jLabel2.setFont(new java.awt.Font("MingLiU-ExtB", 0, 36)); // NOI18N
        jLabel2.setText("PERPUSTAKAAN");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(190, 90, 250, 44);

        mlogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/inside-logout-icon.png"))); // NOI18N
        mlogout.setText("Logout");
        mlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mlogoutActionPerformed(evt);
            }
        });
        jPanel2.add(mlogout);
        mlogout.setBounds(500, 390, 120, 41);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Untuk Petugas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 2, 12))); // NOI18N
        jPanel1.setLayout(null);

        mnpetugas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/add2.png"))); // NOI18N
        mnpetugas.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mnpetugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnpetugasActionPerformed(evt);
            }
        });
        jPanel1.add(mnpetugas);
        mnpetugas.setBounds(30, 30, 60, 60);

        mndinventaris.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/library_folders_files_icon_219441.png"))); // NOI18N
        mndinventaris.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mndinventaris.setMaximumSize(new java.awt.Dimension(36, 36));
        mndinventaris.setMinimumSize(new java.awt.Dimension(36, 36));
        mndinventaris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mndinventarisActionPerformed(evt);
            }
        });
        jPanel1.add(mndinventaris);
        mndinventaris.setBounds(220, 30, 60, 60);

        jLabel5.setText("Data Petugas");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 90, 90, 14);

        jLabel6.setText("Pengembalian");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(210, 90, 90, 14);

        mndaftarbuku1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/education_books_library_icon_149685.png"))); // NOI18N
        mndaftarbuku1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mndaftarbuku1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mndaftarbuku1ActionPerformed(evt);
            }
        });
        jPanel1.add(mndaftarbuku1);
        mndaftarbuku1.setBounds(120, 30, 60, 60);

        jLabel1.setText("Daftar Buku");
        jLabel1.setFocusable(false);
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(120, 90, 70, 14);

        jPanel2.add(jPanel1);
        jPanel1.setBounds(20, 220, 310, 120);

        jPanel3.setBackground(new java.awt.Color(204, 255, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Untuk Anggota", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri Light", 2, 12))); // NOI18N
        jPanel3.setLayout(null);

        mndanggota.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/add2.png"))); // NOI18N
        mndanggota.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mndanggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mndanggotaActionPerformed(evt);
            }
        });
        jPanel3.add(mndanggota);
        mndanggota.setBounds(40, 30, 60, 60);

        mndpinjam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/writing-on-an-open-book_icon-icons.com_70325.png"))); // NOI18N
        mndpinjam.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mndpinjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mndpinjamActionPerformed(evt);
            }
        });
        jPanel3.add(mndpinjam);
        mndpinjam.setBounds(160, 30, 60, 60);

        jLabel7.setText("Data Anggota");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(40, 90, 80, 14);

        jLabel8.setText("Pinjam Buku");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(160, 90, 70, 14);

        jPanel2.add(jPanel3);
        jPanel3.setBounds(340, 220, 260, 120);

        jMenu1.setText("File Master");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        mndsiswa.setText("Data Anggota");
        mndsiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mndsiswaActionPerformed(evt);
            }
        });
        jMenu1.add(mndsiswa);

        mndpetugas.setText("Data Petugas");
        mndpetugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mndpetugasActionPerformed(evt);
            }
        });
        jMenu1.add(mndpetugas);

        mndbuku.setText("Daftar Buku");
        mndbuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mndbukuActionPerformed(evt);
            }
        });
        jMenu1.add(mndbuku);

        jMenuBar1.add(jMenu1);

        transaksi.setText("Transaksi");

        mnpbuku.setText("Peminjaman Buku");
        mnpbuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnpbukuActionPerformed(evt);
            }
        });
        transaksi.add(mnpbuku);

        mnbuku.setText("Pengembalian Buku");
        mnbuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnbukuActionPerformed(evt);
            }
        });
        transaksi.add(mnbuku);

        jMenuBar1.add(transaksi);

        laporan.setText("Laporan");

        mnpengembalian.setText("Pengembalian");
        mnpengembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnpengembalianActionPerformed(evt);
            }
        });
        laporan.add(mnpengembalian);

        jMenuItem4.setText("Peminjaman");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        laporan.add(jMenuItem4);

        jMenuItem6.setText("Data Petugas");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        laporan.add(jMenuItem6);

        jMenuItem7.setText("Data Anggota");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        laporan.add(jMenuItem7);

        jMenuBar1.add(laporan);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mndbukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mndbukuActionPerformed
        // TODO add your handling code here:
        daftarbuku db = new daftarbuku();
        db = new daftarbuku();
        db.setVisible(true);
        db.setLocationRelativeTo(null);
        db.setDefaultCloseOperation(db.EXIT_ON_CLOSE);
    }//GEN-LAST:event_mndbukuActionPerformed

    private void mlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mlogoutActionPerformed
        // TODO add your handling code here:
        NewJFrame njf;
        njf = new NewJFrame();
        njf.setVisible(true);
        njf.pack();
        njf.setLocationRelativeTo(null);
        njf.setDefaultCloseOperation(NewJFrame.EXIT_ON_CLOSE);
        dispose();
    }//GEN-LAST:event_mlogoutActionPerformed

    private void mndsiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mndsiswaActionPerformed
        // TODO add your handling code here:
        datasiswa ds = new datasiswa();
        ds = new datasiswa();
        ds.setVisible(true);
        ds.setLocationRelativeTo(null);
        ds.setDefaultCloseOperation(datasiswa.EXIT_ON_CLOSE);
    }//GEN-LAST:event_mndsiswaActionPerformed

    private void mnpetugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnpetugasActionPerformed
        // TODO add your handling code here:
        datpetugas dp = new datpetugas();
        dp = new datpetugas();
        dp.setVisible(true);
        dp.setLocationRelativeTo(null);
        dp.setDefaultCloseOperation(dp.EXIT_ON_CLOSE);
    }//GEN-LAST:event_mnpetugasActionPerformed

    private void mndpetugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mndpetugasActionPerformed
        // TODO add your handling code here:
       // Hakaksesuser();
        datpetugas dp = new datpetugas();
        dp = new datpetugas();
        dp.setVisible(true);
        //dp.pack();
        dp.setLocationRelativeTo(null);
        dp.setDefaultCloseOperation(dp.EXIT_ON_CLOSE);
        //dispose();
    }//GEN-LAST:event_mndpetugasActionPerformed

    private void mnpbukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnpbukuActionPerformed
        // TODO add your handling code here:
        pinjam pj = new pinjam();
        pj = new pinjam();
        pj.setVisible(true);
        pj.setLocationRelativeTo(null);
        pj.setDefaultCloseOperation(pj.EXIT_ON_CLOSE);
    }//GEN-LAST:event_mnpbukuActionPerformed

    private void mnbukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnbukuActionPerformed
        // TODO add your handling code here:
        //Hakaksespetugas();
        pengembalian pb = new pengembalian();
        pb = new pengembalian();
        pb.setVisible(true);
        //pb.pack();
        pb.setLocationRelativeTo(null);
        pb.setDefaultCloseOperation(pb.EXIT_ON_CLOSE);
        //dispose();
    }//GEN-LAST:event_mnbukuActionPerformed

    private void mnpengembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnpengembalianActionPerformed
        // TODO add your handling code here:
        JasperReport reports;
        
        String path = ".\\src\\laporan\\pengambilan.jasper";
        try {
            reports = (JasperReport) JRLoader.loadObjectFromFile(path);
            JasperPrint jprint = JasperFillManager.fillReport(path, null, conn);
            JasperViewer jviewer = new JasperViewer(jprint, false);
            jviewer.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            jviewer.setVisible(true);
        } catch (JRException ex) {
            Logger.getLogger(menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mnpengembalianActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        JasperReport reports;
        
        String path = ".\\src\\laporan\\datapetugas.jasper";
        try {
            reports = (JasperReport) JRLoader.loadObjectFromFile(path);
            JasperPrint jprint = JasperFillManager.fillReport(path, null, conn);
            JasperViewer jviewer = new JasperViewer(jprint, false);
            jviewer.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            jviewer.setVisible(true);
        } catch (JRException ex) {
            Logger.getLogger(menu.class.getName()).log(Level.SEVERE, null, ex);
        }
         
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
         JasperReport reports;
        
        String path = ".\\src\\laporan\\dataanggota.jasper";
        try {
            reports = (JasperReport) JRLoader.loadObjectFromFile(path);
            JasperPrint jprint = JasperFillManager.fillReport(path, null, conn);
            JasperViewer jviewer = new JasperViewer(jprint, false);
            jviewer.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            jviewer.setVisible(true);
        } catch (JRException ex) {
            Logger.getLogger(menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        JasperReport reports;
        
        String path = ".\\src\\laporan\\peminjaman.jasper";
        try {
            reports = (JasperReport) JRLoader.loadObjectFromFile(path);
            JasperPrint jprint = JasperFillManager.fillReport(path, null, conn);
            JasperViewer jviewer = new JasperViewer(jprint, false);
            jviewer.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            jviewer.setVisible(true);
        } catch (JRException ex) {
            Logger.getLogger(menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void mndinventarisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mndinventarisActionPerformed
        // TODO add your handling code here:
        pengembalian pb = new pengembalian();
        pb = new pengembalian();
        pb.setVisible(true);
        pb.setLocationRelativeTo(null);
        pb.setDefaultCloseOperation(pengembalian.EXIT_ON_CLOSE);
    }//GEN-LAST:event_mndinventarisActionPerformed

    private void mndanggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mndanggotaActionPerformed
        // TODO add your handling code here:
        datasiswa ds = new datasiswa();
        ds = new datasiswa();
        ds.setVisible(true);
        ds.setLocationRelativeTo(null);
        ds.setDefaultCloseOperation(datasiswa.EXIT_ON_CLOSE);
    }//GEN-LAST:event_mndanggotaActionPerformed

    private void mndpinjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mndpinjamActionPerformed
        // TODO add your handling code here:
        pinjam pj = new pinjam();
        pj = new pinjam();
        pj.setVisible(true);
        pj.setLocationRelativeTo(null);
        pj.setDefaultCloseOperation(pj.EXIT_ON_CLOSE);
    }//GEN-LAST:event_mndpinjamActionPerformed

    private void mndaftarbuku1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mndaftarbuku1ActionPerformed
        // TODO add your handling code here:
        daftarbuku db = new daftarbuku();
        db = new daftarbuku();
        db.setVisible(true);
        db.setLocationRelativeTo(null);
        db.setDefaultCloseOperation(db.EXIT_ON_CLOSE);
    }//GEN-LAST:event_mndaftarbuku1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuBar jMenuBar4;
    private javax.swing.JMenuBar jMenuBar5;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JMenu laporan;
    private javax.swing.JButton mlogout;
    private javax.swing.JMenuItem mnbuku;
    private javax.swing.JButton mndaftarbuku1;
    private javax.swing.JButton mndanggota;
    private javax.swing.JMenuItem mndbuku;
    private javax.swing.JButton mndinventaris;
    private javax.swing.JMenuItem mndpetugas;
    private javax.swing.JButton mndpinjam;
    private javax.swing.JMenuItem mndsiswa;
    private javax.swing.JMenuItem mnpbuku;
    private javax.swing.JMenuItem mnpengembalian;
    private javax.swing.JButton mnpetugas;
    private javax.swing.JMenu transaksi;
    // End of variables declaration//GEN-END:variables

}
